version: "3"

services:
  mysql:
    image: mysql:8
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql_conf:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE

  app:
    build:
      context: .
    command: bash -c "bundle update && rails s -p 3000 -b 0.0.0.0"
    environment:
      - RAILS_ENV=development
      - DATABASE_HOST=mysql
    ports:
      - '3000:3000'
    volumes:
      - ".:/app"
    depends_on:
      - "mysql"

volumes:
  dbdata:
