require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe BooksController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # Book. As you add validations to Book, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    FactoryBot.attributes_for :book
  end

  let(:invalid_attributes) do
    FactoryBot.attributes_for :book, price: :a_string
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BooksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'GET #index' do
    it 'returns a success response' do
      book = Book.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'GET #show' do
    it 'returns a success response' do
      book = Book.create! valid_attributes
      get :show, params: { id: book.to_param }, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'POST #create' do
    let(:current_user) { FactoryBot.create :user }
      before(:each) do
        request.headers.merge! current_user.create_new_auth_token
      end
    context 'with valid params' do
      it 'creates a new Book' do
        expect do
          post :create, params: { book: valid_attributes }, session: valid_session
        end.to change(Book, :count).by(1)
      end

      it 'renders a JSON response with the new book' do
        post :create, params: { book: valid_attributes }, session: valid_session
        expect(response).to have_http_status(:created)
        expect(response.content_type).to eq('application/json')
        expect(response.location).to eq(book_url(Book.last))
      end
    end

    context 'with invalid params' do
      it 'renders a JSON response with errors for the new book' do
        post :create, params: { book: invalid_attributes }, session: valid_session
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq('application/json')
      end
    end
  end

  describe 'PUT #update' do
    let(:new_attributes) {{ name: :foo_baz }}
    let(:current_user) { FactoryBot.create :user }
    before(:each) do
      request.headers.merge! current_user.create_new_auth_token
    end

    context 'with valid params' do

      it 'updates the requested book' do
        book = Book.create! valid_attributes
        book.update_attributes(user: current_user)
        put :update, params: { id: book.to_param, book: new_attributes }, session: valid_session
        book.reload
        expect(book.name).to eq('foo_baz')
      end

      it 'renders a JSON response with the book' do
        book = Book.create! valid_attributes
        book.update_attributes(user: current_user)
        put :update, params: { id: book.to_param, book: valid_attributes }, session: valid_session
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to eq('application/json')
      end
    end

    context 'with invalid params' do
      it 'renders a JSON response with errors for the book' do
        book = Book.create! valid_attributes
        book.update_attributes(user: current_user)
        put :update, params: { id: book.to_param, book: invalid_attributes }, session: valid_session
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq('application/json')
      end
    end

    context 'with current user is not the book creator' do
      it 'will not update the requested book record' do
        book = Book.create! valid_attributes
        put :update, params: { id: book.to_param, book: new_attributes }
        book.reload
        expect(book.name).not_to eq('foo_baz')
      end

      it 'renders a JSON respons with 401 unauthorized' do
        book = Book.create! valid_attributes
        put :update, params: { id: book.to_param, book: new_attributes }
        expect(response).to have_http_status(:unauthorized)
        expect(response.content_type).to eq('application/json')
      end
    end
  end

  describe 'DELETE #destroy' do
    let(:current_user) { FactoryBot.create :user }
    before(:each) do
      request.headers.merge! current_user.create_new_auth_token
    end
    it 'destroys the requested book' do
      book = Book.create! valid_attributes
      book.update_attributes(:user => current_user)
      expect do
        delete :destroy, params: { id: book.to_param }, session: valid_session
      end.to change(Book, :count).by(-1)
    end

    it 'will not destroy book if current user is not the book creator' do
      book = Book.create! valid_attributes
      expect do
        delete :destroy, params: { id: book.to_param }, session: valid_session
      end.not_to change(Book, :count)
    end
  end
end
